name: Build & SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: borya-chip
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Build lab_1
        run: |
          rm -rf lab_1/build
          mkdir lab_1/build
          cmake -S lab_1 -B lab_1/build 
          build-wrapper-linux-x86-64 --out-dir lab_1/build_wrapper cmake --build lab_1/build --config Release

      - name: Build lab_2
        run: |
          rm -rf lab_2/build
          mkdir lab_2/build
          cmake -S lab_2 -B lab_2/build 
          build-wrapper-linux-x86-64 --out-dir lab_2/build_wrapper cmake --build lab_2/build --config Release

      - name: Build lab_3
        run: |
          rm -rf lab_3/build
          mkdir lab_3/build
          cmake -S lab_3 -B lab_3/build 
          build-wrapper-linux-x86-64 --out-dir lab_3/build_wrapper cmake --build lab_3/build --config Release

      - name: Build lab_4
        run: |
          rm -rf lab_4/build
          mkdir lab_4/build
          cmake -S lab_4 -B lab_4/build 
          build-wrapper-linux-x86-64 --out-dir lab_4/build_wrapper cmake --build lab_4/build --config Release

      - name: Build lab_5
        run: |
          rm -rf lab_5/build
          mkdir lab_5/build
          cmake -S lab_5 -B lab_5/build 
          build-wrapper-linux-x86-64 --out-dir lab_5/build_wrapper cmake --build lab_5/build --config Release
          
      - name: Build lab_6
        run: |
          rm -rf lab_6/build
          mkdir lab_6/build
          cmake -S lab_6 -B lab_6/build 
          build-wrapper-linux-x86-64 --out-dir lab_6/build_wrapper cmake --build lab_6/build --config Release

      - name: SonarCloud scan lab_1
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_lab1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_1
            -Dsonar.cfamily.compile-commands=lab_1/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true

      - name: SonarCloud scan lab_2
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_lab2
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_2
            -Dsonar.cfamily.compile-commands=lab_2/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true

      - name: SonarCloud scan lab_3
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_lab3
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_3
            -Dsonar.cfamily.compile-commands=lab_3/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true      

      - name: SonarCloud scan lab_4
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_lab4
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_4
            -Dsonar.cfamily.compile-commands=lab_4/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true  

      - name: SonarCloud scan lab_5
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_labs
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_5
            -Dsonar.cfamily.compile-commands=lab_5/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true      

      - name: SonarCloud scan lab_6
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=borya-chip_cpp_labs
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=lab_6
            -Dsonar.cfamily.compile-commands=lab_6/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true   